services:
  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - ./logs:/var/log:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    depends_on:
      - loki
