server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: express-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: express-app
          __path__: /var/log/app-*.log
    
    # Extract environment from filename
    pipeline_stages:
      - regex:
          expression: '/var/log/app-(?P<environment>\w+)\.log'
      - labels:
          environment:
