# k8s/grafana-values.yaml
adminPassword: admin

# Resource limits for local development
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

# Single replica for local
replicas: 1

grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.infra-ns-node-text-analyzer.svc.cluster.local:3100
        version: 1
        editable: false

# Disable persistence to save disk space
persistence:
  enabled: false
