# k8s/loki-values.yaml
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  extraArgs:
    - -config.expand-env=true

# Disable all other modes
simpleScalable:
  ingester: { replicas: 0 }
  distributor: { replicas: 0 }
  querier: { replicas: 0 }
  queryFrontend: { replicas: 0 }
  compactor: { replicas: 0 }
  indexGateway: { replicas: 0 }
backend: { replicas: 0 }
read: { replicas: 0 }
write: { replicas: 0 }

# Loki config
loki:
  auth_enabled: false          #     Disable multi-tenancy for local dev
                               #     This removes the need for X-Scope-OrgID headers,
                               #     fixing the "no org id" error in Grafana Explore.
  persistence:
    enabled: false             # No PVCs for local/dev (same as before)
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
    filesystem:
      directory: /var/loki/chunks
  memberlist:
    join_members: []
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  distributor:
    ring:
      kvstore:
        store: inmemory

limits_config:
  retention_period: 24h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h

minio:
  enabled: false
